development:
  adapter: postgresql
  host: localhost
  database: karmaville_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: karmaville_test
  pool: 5
  timeout: 5000